title: WeBat
name: WeBat s.r.o.
email: alex.ostrovsky@webat.sk
description: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.

baseurl: ""
url: "http://webat.sk"

parallax_image_one: assets/images/contact2-test.jpg

project_one: FASHY
project_one_url: http://www.fashy.sk
project_one_description: FASHY your fashy blog. 

project_two: Promenu
project_two_url: http://www.promenu.sk
project_two_description: Objav ďalšie reštaurácie v tvojom okolí v Slovensko. Na portáli promenu.sk nájdete obedové menu, denné menu , jedálny lístok a zoznam reštaurácií na Slovensku, Reštaurácie, akcie, príspevky.

project_three: Kia Motors
project_three_url: http://www.kia.com
project_three_description: Kia. The Power to Surprise

project_four: Actionfraud
project_four_url: https://www.actionfraud.police.uk
project_four_description: ActionFraud is the UK’s national fraud and cyber crime reporting centre.

portfolio_heading: Portfolio

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: angularjs
  - name: apple
  - name: bootstrap
  - name: coffeescript
  - name: confluence
  - name: css3
  - name: docker
  - name: git
  - name: github
  - name: gitlab
  - name: go
  - name: html5
  - name: intelliJ
  - name: java
  - name: javascript
  - name: jquery
  - name: linux
  - name: mysql
  - name: nginx
  - name: nodejs
  - name: php
  - name: protractor
  - name: postgresql
  - name: python
  - name: rails
  - name: ruby
  - name: sass
  - name: slack
  - name: ssh
  - name: ubuntu
  - name: visualstudio
  - name: vuejs
  - name: webpack
  - name: wordpress

icon_size: 50
colored: colored

project_button: Web

github: https://github.com/jameshamann/jekyll-material-theme
medium: https://medium.com

baseurl: 
url: http://localhost:4000/

syntax_highlighting: true

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-assets
  - jekyll-minifier
